version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  build-deploy:
    executor:
      name: node/default
      tag: '12.11.0'
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run:
          name: Deploying
          command: node ./ftp-deploy.js $host $user $password

workflows:
  version: 2
  main:
    jobs:
      - build-deploy:
          filters:
            branches:
              only: master